### ISSUE TITLE
Understanding Parameters in GeNN comparison

### ISSUE THREAD

**Issue by denniskb** [nasiryahm/SNNSimulatorComparison#2]
I'm trying to understand the 'parameters.h' files for [VA](https://github.com/nasiryahm/SNNSimulatorComparison/blob/master/Benchmarks/VogelsAbbott/genn/parameters.h) and [Brunel](https://github.com/nasiryahm/SNNSimulatorComparison/blob/master/Benchmarks/Brunel/genn/parameters.h) inside the GeNN comparison.

- In the VA case, you scale all constants by a factor of 1000 (which allows you to work in mV rather than V?), except the synaptic weights, which you scale by 1/1000.
- In the Brunel case, you scale all constants by a factor of 1000 (incl. synaptic weights), except the timestep, which you scale by 100.

Thank you for clarifying!

**Comment by denniskb** [comment]
I understand now that the timestep in Brunel is in milliseconds, so the whole params.h file makes perfect sense. I still can't wrap my head around the timestep and the synaptic weights in VA though.

**Comment by nasiryahm** [comment]
Hi Dennis,

Glad to hear the Brunel parameters make sense. 

In the case of the synaptic parameters for the VA model, the effect on membrane voltage is equal to the synaptic current times the membrane resistance. In turn the membrane resistance can be calculated:

membrane resistance = membrane time constant / membrane capacitance

This capacitance and time constant parameters are located here:
https://github.com/nasiryahm/SNNSimulatorComparison/blob/master/Benchmarks/VogelsAbbott/genn/model.cc#L32

Once you multiply these through, it works out to an impact on the voltage in the mV scale. You should also note that the Brunel benchmark doesn't need these conversions since the synapses are voltage based.

Does that all make sense?

**Comment by denniskb** [comment]
Dear Nasir, thank you for the clarifications. I built your code (genn-vogels), ran a 20s long simulation, outputted the spikes to a txt file and [visualized them with Matlab](https://drive.google.com/file/d/1B5INtqfAUSsayJU5Cjq7le5NsBzpy9FF/view?usp=sharing). I noticed a pretty high network activity, so I calculated the average firing rate as:

`number of spikes per sim. step / number of steps / number of neurons`

which came out to ~0.14 or 14%. Shouldn't this be capped to 2% due the refractory period of 50 timesteps?

**Comment by denniskb** [comment]
It seems to me that the `timestep` inside the [VA parameters.h file](https://github.com/nasiryahm/SNNSimulatorComparison/blob/master/Benchmarks/VogelsAbbott/genn/parameters.h) should be `0.1` instead of `1.0`.

**Comment by nasiryahm** [comment]
Hi Dennis,

It's rather strange that you are getting high firing rates. Especially since in the iPython notebook in this repository, I check all firing rates and ISIs. You can see the notebook:

https://github.com/nasiryahm/SNNSimulatorComparison/blob/master/Benchmarks/VogelsAbbott/_results/SimulatorComparisons.ipynb

Can you check that you are using the same version of GeNN that is a submodule in this repository?

As for the time step, you are quite right, that should be 0.1. However, I am not actually using that parameter at the moment. I instead directly set the time step in the model.cc file in the GeNN folder. I should make that more transparent.

**Comment by denniskb** [comment]
I accidentally replaces `setDT(0.1` with `setDT(params::timestep)`!

**Comment by nasiryahm** [comment]
Ah okay! Glad to hear it worked out :) - I'll fix that in the repository later today so that the parameter is used and is set to 0.1ms.

Thank for pointing it out!
